export const routerBreakcrumbList = [{
  path: '/home',
  component: './Home/Home',
  title: '首页',
  breadcrumb: '首页',
},
{
  path: '/home/react_component',
  component: './Users/Users',
  title: 'React声明周期',
  breadcrumb: 'React声明周期',
},
{
  path: '/home/product_edit',
  component: './DynamicForm/DynamicForm',
  title: '编辑商品',
  breadcrumb: '编辑商品',
},
{
  path: '/home/ui',
  component: './Ui/Ui',
  title: 'Ui',
  breadcrumb: 'Ui',
},
{
  path: '/home/ui/button',
  component: './Ui/Button/Button',
  title: 'Button',
  breadcrumb: 'Button',
},
{
  path: '/home/ui/modal',
  component: './Ui/Modal/Modal',
  title: 'Modal',
  breadcrumb: '弹框',
},
{
  path: '/home/ui/loading',
  component: './Ui/Loading/Loading',
  title: 'Loading',
  breadcrumb: 'Loading',
},
{
  path: '/home/ui/notification',
  component: './Ui/Notification/Notification',
  title: 'Notification',
  breadcrumb: '通知提醒',
},
{
  path: '/home/ui/message',
  component: './Ui/Message/Message',
  title: 'Message',
  breadcrumb: '全局Message',
},
{
  path: '/home/ui/tab',
  component: './Ui/tab/tab',
  title: 'tab',
  breadcrumb: 'Tab页签',
},
{
  path: '/home/form',
  component: './Form/Form',
  title: 'form',
  breadcrumb: '表单',
},
{
  path: '/home/form/login',
  component: "./Form/Login/Login",
  title: '登录',
  breadcrumb: '登录',
},
{
  path: '/home/form/reg',
  component: "./Form/Register/Register",
  title: '注册',
  breadcrumb: '注册',
},

]
